### ISSUE TITLE
Not getting Unread items badge

### ISSUE THREAD

**Issue by SkepticSpoon** [annagrram/recipe-inoreader#1]
Hello. I imported this recipe into Ferdi (a fork of Franz), but it doesn't show the no. of unread items in the icon. I was wondering if this was possible to be fixed?

Thank you!

**Comment by annagrram** [comment]
Hi.

Wow. I haven't touched Franz nor this recipe in ages.

I've downloaded Ferdi and fixed the issue.

Please let me know if it works for you.

Thanks for the report!

**Comment by SkepticSpoon** [comment]
It works! Thank you so much!!

**Comment by annagrram** [comment]
Glad to hear :)

My pleasure.
